### ISSUE TITLE
PlayList Name isn't resetting on state change

### ISSUE THREAD

**Issue by farishkash** [armandocapo/jamming#1]
https://github.com/armandocapo/jamming/blob/32c28e7b016fa959f7e1b301818806d4d636f7d3/src/components/Playlist/Playlist.js#L21

The problem is happening here.  The title is not getting updated with the playList Name on save because the item is already render.  You would have to change this slightly to force this to update.  Maybe using componentDidUpdate in the constructor.

**Comment by armandocapo** [comment]
I noticed that it did not update right away. I forgot about componentDidUpdate. Thanks again!
