### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by farishkash** [armandocapo/jamming#2]
https://github.com/armandocapo/jamming/blob/32c28e7b016fa959f7e1b301818806d4d636f7d3/src/components/App/App.js#L53

A multi value object shouldn't be on one line.   This makes harder to notice a missing colon, comma or potentially other errors.

Also you should be putting your jsx components on multiple lines when they have multiple props.  

The goal here is better readability.  You may want to look at the airbnb style guide for react.

Your savePlaylist and Playlist component code reformatted below.

```
 savePlaylist() {
    let trackURIs = this.state.playlistTracks.map(track => track.uri);
    if (trackURIs && this.state.playlistName && trackURIs.length > 0) {
      Spotify.savePlaylist(this.state.playlistName, trackURIs).then(() => {
        this.setState({
          playlistName: "New Playlist",
          playlistTracks: [],
          searchResults: [],
          trackURIs: []
        });
      });
      console.log(this.state.playlistName);
    }
  }
```

```
            <Playlist
              title={this.state.playlistName}
              onNameChange={this.updatePlaylistName}
              onSave={this.savePlaylist}
              tracks={this.state.playlistTracks}
              onRemove={this.removeTrack}
              onAdd={this.addTrack}
            />
```

**Comment by armandocapo** [comment]
I will take a look at the Airbnb style guide. Thanks again.
